backend:
  name: git-gateway
  repo: RedCiudadana/WebJH2025
  branch: main
  identity_url: https://auth.decapbridge.com/sites/9bc372f7-2fef-4758-9bf8-254084cfdbd7
  gateway_url: https://gateway.decapbridge.com

  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blogs"
    label: "Blogs"
    folder: "src/content/blogs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre", name: "title", widget: "string" }
      - { label: "Thumbnail", name: "image", widget: "image" }
      - { label: "Descripción General", name: "descripcion", widget: "text" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "author", label: "Author" }
      - {
          name: "highlight",
          label: "Highlight",
          widget: "boolean",
          default: false,
        }
  - name: "proyectos"
    label: "Proyectos"
    folder: "src/content/proyectos"
    create: true
    slug: "{{slug}}"
    fields:
    - { label: "Nombre", name: "title", widget: "string" }
      - { label: "Thumbnail", name: "image", widget: "image" }
      - { label: "Descripción General", name: "descripcion", widget: "text" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { label: "Institucion", name: "institucion", widget: "string" }
      - { label: "Categoria", name: "categoria", widget: "string" }
      - { label: "Enlace", name: "enlace", widget: "string" }
      - {
          name: "highlight",
          label: "Highlight",
          widget: "boolean",
          default: false,
        }
      
